name: Omni - Test suite

on: push

jobs:
    All:
        name: All tests
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: jiro4989/setup-nim-action@v1
              with:
                  nim-version: 'stable'
            - run: nimble install -Y
            - run: nimble test -Y
